### ISSUE TITLE
[Request] Accept path strings in template and blueprint fields

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-rs#22]
Would be great if resource path strings (eg. `[assembly:/whatever.entity].pc_entitytype`) would be accepted for the `tempHash` and `tbluHash` fields (or some alternative to them), and QN would automatically hash them, in the same way it does for references.

**Comment by bennett-sh** [comment]
Any updates on this?

**Comment by atampy25** [comment]
I think this was actually resolved on RPKG's side with that commit a while ago
