### ISSUE TITLE
SMatrix43 encoding is missing properties like scale

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-rs#23]
Transformations stored in 4x3 (or sometimes 4x4) matrices, and hence the `SMatrix43` name, encode a lot more information than just rotation and translation. The current QN encoding of `SMatrix43` only contains `rotation` (in what I assume is yaw - pitch - roll encoding?) and `position` (translation), and is missing things like scale and shear (there might be more but I'm not sure).

**Comment by OrfeasZ** [comment]
A few more notes: it's unlikely the game makes use of anything other than scale, but you never know. Generally I'd suggest against re-encoding these values, since you lose information in the process, and they were never meant to be modified by hand anyway (not anything other than the translation at least). 

What you could do is keep the rotation / scale / whatever part as - is and have the translation component separately. Alternatively, if you don't care about losing information, you can verify which of these components are actually used by the game and try to separate them all out of the matrix (so basically adding a scale property, etc.).

**Comment by atampy25** [comment]
QN now decomposes the matrix into scale as well as rotation and position. Skew isn't much of a concern; I don't believe it's used anywhere (even scale isn't actually used for anything most of the time).
